site_name: Constitution of India
site_url: https://www.patashale.in/coi/
site_author: Patashale™
site_description: Educate yourself with Constitution of India and practice it in real world.
repo_url: https://github.com/patashale/coi
repo_name: patashale/coi
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.footer

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/patashale
      name: Patashale™ on LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/patashale
      name: Patashale™ on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/patashale_in
      name: Patashale™ on Twitter
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@patashale
      name: Patashale™ on Mastodon Social
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@patashale
      name: Patashale™ on Fosstodon
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@patashale
      name: Patashale™ on YouTube
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@constitution-of-india
      name: Constitution of India on YouTube

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Know before you start: index.md
  - Preamble: en/preamble.md
  - Part 1 - The Union and its territory:
    - Article 1: en/1.md
    - Article 2: en/2.md
    - Article 3: en/3.md
    - Article 4: en/4.md
  - Part 2 - Citizenship:
    - Article 5: en/5.md
    - Article 6: en/6.md
    - Article 7: en/7.md
    - Article 8: en/8.md
    - Article 9: en/9.md
    - Article 10: en/10.md
    - Article 11: en/11.md

copyright: <a property="dct:title" rel="cc:attributionURL" href="https://www.patashale.in/coi">Constitution of India</a> by <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="https://www.github.com/patashale">Patashale™</a> is licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-SA 4.0</a> & <a href="https://www.gnu.org/licenses/agpl-3.0" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">AGPL 3.0</a>
