site_name: Constitution of India
site_url: https://www.patashale.in/coi/
site_author: Patashale™
site_description: Educate yourself with Constitution of India and practice it in real world.
repo_url: https://github.com/patashale/coi
repo_name: patashale/coi
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.footer

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/patashale
      name: Patashale™ on LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/patashale
      name: Patashale™ on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/patashale_in
      name: Patashale™ on Twitter
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@patashale
      name: Patashale™ on Mastodon Social
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@patashale
      name: Patashale™ on Fosstodon
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@patashale
      name: Patashale™ on YouTube
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@constitution-of-india
      name: Constitution of India on YouTube

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Know before you start: index.md
  - Preamble: en/preamble.md
  - Part 1 - The Union and its territory:
    - Article 1: en/1.md
    - Article 2: en/2.md
    - Article 3: en/3.md
    - Article 4: en/4.md
  - Part 2 - Citizenship:
    - Article 5: en/5.md
    - Article 6: en/6.md
    - Article 7: en/7.md
    - Article 8: en/8.md
    - Article 9: en/9.md
    - Article 10: en/10.md
    - Article 11: en/11.md
  - Part 3 - Fundamental rights:
    - General:
      - Article 12: en/12.md
      - Article 13: en/13.md
    - Right to equality:
      - Article 14: en/14.md
      - Article 15: en/15.md
      - Article 16: en/16.md
      - Article 17: en/17.md
      - Article 18: en/18.md
    - Right to freedom:
      - Article 19: en/19.md
      - Article 20: en/20.md
      - Article 21: en/21.md
      - Article 21A: en/21A.md
      - Article 22: en/22.md
    - Right to exploitation:
      - Article 23: en/23.md
      - Article 24: en/24.md
    - Right to religion:
      - Article 25: en/25.md
      - Article 26: en/26.md
      - Article 27: en/27.md
      - Article 28: en/28.md
    - Cultural and educational rights:
      - Article 29: en/29.md
      - Article 30: en/30.md
    - Saving of certain laws:
      - Article 31A: en/31A.md
      - Article 31B: en/31B.md
      - Article 31C: en/31C.md
    - Right to constitutional remedies:
      - Article 32: en/32.md
      - Article 33: en/33.md
      - Article 34: en/34.md
      - Article 35: en/35.md
  - Part 4 - Directive principles of state policy:
    - Article 36: en/36.md
    - Article 37: en/37.md
    - Article 38: en/38.md
    - Article 39: en/39.md
    - Article 39A: en/39A.md
    - Article 40: en/40.md
    - Article 41: en/41.md
    - Article 42: en/42.md
    - Article 43: en/43.md
    - Article 43A: en/43A.md
    - Article 43B: en/43B.md
    - Article 44: en/44.md
    - Article 45: en/45.md
    - Article 46: en/46.md
    - Article 47: en/47.md
    - Article 48: en/48.md
    - Article 48A: en/48A.md
    - Article 49: en/49.md
    - Article 50: en/50.md
    - Article 51: en/51.md

copyright: <a property="dct:title" rel="cc:attributionURL" href="https://www.patashale.in/coi">Constitution of India</a> by <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="https://www.github.com/patashale">Patashale™</a> is licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-SA 4.0</a> & <a href="https://www.gnu.org/licenses/agpl-3.0" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">AGPL 3.0</a>
